services:

  gitserver:
    build: 
      context: ${PWD}/build
    restart: always
    container_name: gitserver
    ports:
      - "2222:22"
    volumes:
      - ${PWD}/data/ssh:/srv/ssh
      - ${PWD}/config.yml:/srv/config.yml
      - ${PWD}/data/home:/home

